controllers:
  resource:
    path: ../src/Presentation/Http/App/Controller
    namespace: App\Presentation\Http\App\Controller
  type: attribute

app_articles:
  path: /article
  controller: App\Presentation\Http\App\Controller\Frontpage\ArticleController::index

app_show_article:
  path: /article/{id}
  controller: App\Presentation\Http\App\Controller\Frontpage\ArticleController::show
